---
polls:
  - name: 'simple-example'
    title: 'A simple example'
    desc: 'An example of a poll description and how to explain ambiguities to users.'
    options:
      - label: 'Option 1'
        value: 'op1'
      - label: 'Option 2'
        value: 'op2'
      - label: 'Option 3'
        value: 'op3'
      - label: 'Option 4'
        value: 'op4'
  - name: 'best-pet'
    title: 'What''s the best pet to have at home?'
    desc: 'Deciding what you next pet is going to be is an important thing, choose wisely!'
    options:
      - label: 'Cat'
        value: 'cat'
      - label: 'Dog'
        value: 'dog'
      - label: 'Bird'
        value: 'bird'
      - label: 'Snake'
        value: 'snake'
  - name: 'worst-pet'
    title: 'What''s the worst pet to have at home?'
    desc: 'Deciding what you next pet is going to be is an important thing, choose wisely!'
    options:
      - label: 'Bat'
        value: 'bat'
      - label: '<b>Squirrel</b>'
        value: 'squirrel'
      - label: 'Mosquitto'
        value: 'mosquitto'
      - label: 'Spider'
        value: 'spider'
      - label: 'Wasp'
        value: 'wasp'
